# Generated by Django 4.0.5 on 2022-08-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout',
            name='category',
        ),
    ]
