# Generated by Django 4.0.5 on 2022-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_scoutcourse_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='playeruploadid',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
    ]
