# Generated by Django 4.0.5 on 2022-08-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_scout_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interkart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='document_id_selected',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='group',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='primary_position',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='season',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='secondary_position',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='state',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='tournament_city',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='tournament_state',
        ),
        migrations.RemoveField(
            model_name='interkart',
            name='whoisfilling',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='scout',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.scoutcourse', verbose_name='Course'),
        ),
        migrations.DeleteModel(
            name='Interkart',
        ),
    ]
