# Generated by Django 4.0.5 on 2022-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_scout_playeruploadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='playeruploadid',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
