# Generated by Django 4.0.5 on 2022-09-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_scout_playeruploadid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='extrafield1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scout',
            name='extrafield2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scout',
            name='pan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
