# Generated by Django 4.0.5 on 2022-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_scout_extrafield1_scout_extrafield2_scout_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='extrafield3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scout',
            name='extrafield4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
